
import type { Toilet, UserProfile } from './types';

// Mock User Profiles for Leaderboard
export const mockUserProfiles: UserProfile[] = [
  {
    id: 'user_abc123',
    displayName: 'ToiletTamer78',
    joinedAt: new Date().toISOString(),
    contributions: 52,
    isAdmin: false,
    profilePhotoUrl: 'https://picsum.photos/seed/user1/100/100',
    countryCode: 'US',
    countryFlag: '🇺🇸',
    badge: 'Loo Legend',
  },
  {
    id: 'user_def456',
    displayName: 'WandaWipe',
    joinedAt: new Date().toISOString(),
    contributions: 47,
    isAdmin: false,
    profilePhotoUrl: 'https://picsum.photos/seed/user2/100/100',
    countryCode: 'GB',
    countryFlag: '🇬🇧',
    badge: 'Porcelain Pioneer',
  },
  {
    id: 'user_ghi789',
    displayName: 'BidetBoss',
    joinedAt: new Date().toISOString(),
    contributions: 43,
    isAdmin: false,
    profilePhotoUrl: 'https://picsum.photos/seed/ghiboss/100/100',
    countryCode: 'FR',
    countryFlag: '🇫🇷',
    badge: 'Top Tier Tiler',
  },
  {
    id: 'user_jkl012',
    displayName: 'FlushMasterFlex',
    joinedAt: new Date().toISOString(),
    contributions: 35,
    isAdmin: false,
    profilePhotoUrl: 'https://picsum.photos/seed/user3/100/100',
    countryCode: 'DE',
    countryFlag: '🇩🇪',
  },
  {
    id: 'user_mno345',
    displayName: 'SanitationSavvy',
    joinedAt: new Date().toISOString(),
    contributions: 30,
    isAdmin: false,
    profilePhotoUrl: 'https://picsum.photos/seed/savvysan/100/100',
    countryCode: 'JP',
    countryFlag: '🇯🇵',
  },
  {
    id: 'user_pqr678',
    displayName: 'DutchDunker',
    joinedAt: new Date().toISOString(),
    contributions: 28,
    isAdmin: false,
    profilePhotoUrl: 'https://picsum.photos/seed/dunker/100/100',
    countryCode: 'NL',
    countryFlag: '🇳🇱',
    badge: 'Canal Cleaner',
  },
  {
    id: 'user_stu901',
    displayName: 'AussieLooReviewer',
    joinedAt: new Date().toISOString(),
    contributions: 25,
    isAdmin: false,
    profilePhotoUrl: 'https://picsum.photos/seed/aussieloo/100/100',
    countryCode: 'AU',
    countryFlag: '🇦🇺',
  },
  {
    id: 'user_vwx234',
    displayName: 'CanadianCanExplorer',
    joinedAt: new Date().toISOString(),
    contributions: 22,
    isAdmin: false,
    profilePhotoUrl: 'https://picsum.photos/seed/canadiancan/100/100',
    countryCode: 'CA',
    countryFlag: '🇨🇦',
  },
  {
    id: 'user_yza567',
    displayName: 'KiwiCommodeCritic',
    joinedAt: new Date().toISOString(),
    contributions: 19,
    isAdmin: false,
    profilePhotoUrl: 'https://picsum.photos/seed/user4/100/100',
    countryCode: 'NZ',
    countryFlag: '🇳🇿',
  },
  {
    id: 'user_bcd890',
    displayName: 'SpanishStallSurfer',
    joinedAt: new Date().toISOString(),
    contributions: 15,
    isAdmin: false,
    profilePhotoUrl: 'https://picsum.photos/seed/spanishstall/100/100',
    countryCode: 'ES',
    countryFlag: '🇪🇸',
  }
];


export const mockToilets: Toilet[] = [
  {
    id: '1',
    name: 'Starbucks, Main Street',
    location: { latitude: 51.5075, longitude: -0.1278 },
    address: '123 Main St, London, UK',
    createdBy: 'user_def456', // WandaWipe
    createdAt: '2023-10-01T10:00:00Z',
    averageRating: 4.2,
    features: {
      accessible: true, babyChanging: false, free: true, genderNeutral: false, hasSoap: true, hasToiletPaper: true,
    },
    photoUrls: ['https://picsum.photos/seed/toilet1/400/300'],
    reviewCount: 28,
    countryCode: 'GB',
    countryFlag: '🇬🇧',
    legacyReview: 'Surprisingly clean for a busy coffee shop!',
  },
  {
    id: '2',
    name: 'Central Park Secret Restroom',
    location: { latitude: 51.5090, longitude: -0.1200 },
    address: 'Near the Big Oak, Central Park, London, UK',
    createdBy: 'user_def456', // WandaWipe
    createdAt: '2023-10-02T11:00:00Z',
    averageRating: 2.1,
    features: {
      accessible: false, babyChanging: false, free: true, genderNeutral: true, hasSoap: false, hasToiletPaper: false,
    },
    photoUrls: ['https://picsum.photos/seed/toilet2/400/300'],
    reviewCount: 12,
    countryCode: 'GB',
    countryFlag: '🇬🇧',
    legacyReview: 'Beware the raccoon. And bring your own TP.',
  },
  {
    id: '3',
    name: 'Luxury Hotel Loo',
    location: { latitude: 51.5050, longitude: -0.1250 },
    address: '5 Grand Plaza, London, UK',
    createdBy: 'user_abc123', // ToiletTamer78 (US based, reviewing in UK)
    createdAt: '2023-10-03T12:00:00Z',
    averageRating: 4.9,
    features: {
      accessible: true, babyChanging: true, free: true, genderNeutral: true, hasSoap: true, hasToiletPaper: true,
    },
    photoUrls: ['https://picsum.photos/seed/toilet3/400/300'],
    reviewCount: 45,
    countryCode: 'GB',
    countryFlag: '🇬🇧',
    legacyReview: 'Felt like a king on this throne! Marble everywhere.',
  },
  {
    id: '4',
    name: 'Gas Station Gamble',
    location: { latitude: 51.5123, longitude: -0.1345 },
    address: 'Highway A1, Exit 4, Near London',
    createdBy: 'user_def456',
    createdAt: '2023-10-04T13:00:00Z',
    averageRating: 1.0, // Changed from 1.5 to 1.0
    features: {
      accessible: false, babyChanging: false, free: false, genderNeutral: false, hasSoap: false, hasToiletPaper: false,
    },
    photoUrls: ['https://picsum.photos/seed/toilet4/400/300'],
    reviewCount: 5,
    countryCode: 'GB',
    countryFlag: '🇬🇧',
    legacyReview: 'Only if you are absolutely desperate. And brave. Very brave.',
  },
  {
    id: '5',
    name: 'Quirky Cafe Comfort Station',
    location: { latitude: 48.8566, longitude: 2.3522 }, // Paris
    address: '1 Rue de Rivoli, Paris, France',
    createdBy: 'user_ghi789', // BidetBoss
    createdAt: '2023-10-05T14:00:00Z',
    averageRating: 3.3,
    features: {
      accessible: false, babyChanging: false, free: true, genderNeutral: true, hasSoap: true, hasToiletPaper: true,
    },
    photoUrls: ['https://picsum.photos/seed/toilet5/400/300'],
    reviewCount: 18,
    countryCode: 'FR',
    countryFlag: '🇫🇷',
    legacyReview: 'Interesting decor, a bit small but functional.',
  },
  {
    id: '6',
    name: 'Tokyo Public Marvel',
    location: { latitude: 35.6895, longitude: 139.6917 }, // Tokyo
    address: 'Shibuya Crossing, Tokyo, Japan',
    createdBy: 'user_mno345', // SanitationSavvy
    createdAt: '2023-10-06T15:00:00Z',
    averageRating: 5.0,
    features: {
      accessible: true, babyChanging: true, free: true, genderNeutral: true, hasSoap: true, hasToiletPaper: true,
    },
    photoUrls: ['https://picsum.photos/seed/toilet6/400/300'],
    reviewCount: 72,
    countryCode: 'JP',
    countryFlag: '🇯🇵',
    legacyReview: 'Cleaner than my own home. Heated seats!',
  },
  {
    id: '7',
    name: 'Amsterdam Canal Convenience',
    location: { latitude: 52.370216, longitude: 4.895168 }, // Amsterdam
    address: 'Prinsengracht 263, Amsterdam, Netherlands',
    createdBy: 'user_pqr678', // DutchDunker
    createdAt: '2023-10-07T16:00:00Z',
    averageRating: 3.8,
    features: {
      accessible: false, babyChanging: false, free: true, genderNeutral: false, hasSoap: true, hasToiletPaper: true,
    },
    photoUrls: ['https://picsum.photos/seed/toilet7/400/300'],
    reviewCount: 22,
    countryCode: 'NL',
    countryFlag: '🇳🇱',
    legacyReview: 'Good for a quick stop, watch your step!',
  },
  {
    id: '8',
    name: 'Berlin Art Loo',
    location: { latitude: 52.520008, longitude: 13.404954 }, // Berlin
    address: 'East Side Gallery, Berlin, Germany',
    createdBy: 'user_jkl012', // FlushMasterFlex
    createdAt: '2023-10-08T17:00:00Z',
    averageRating: 4.1,
    features: {
      accessible: true, babyChanging: false, free: false, genderNeutral: true, hasSoap: true, hasToiletPaper: false,
    },
    photoUrls: ['https://picsum.photos/seed/toilet8/400/300'],
    reviewCount: 31,
    countryCode: 'DE',
    countryFlag: '🇩🇪',
    legacyReview: 'Very artsy, but bring your own paper towels.',
  },
  {
    id: '9',
    name: 'Horror Show Public Restroom',
    location: { latitude: 51.5000, longitude: -0.1000 },
    address: 'Unknown Alley, London, UK',
    createdBy: 'user_def456',
    createdAt: '2023-10-09T10:00:00Z',
    averageRating: 1.0,
    features: {
      accessible: false, babyChanging: false, free: true, genderNeutral: false, hasSoap: false, hasToiletPaper: false,
    },
    photoUrls: ['https://picsum.photos/seed/toilet9horror/400/300'],
    reviewCount: 3,
    countryCode: 'GB',
    countryFlag: '🇬🇧',
    legacyReview: 'Avoid at all costs. I think something lives in there.',
  },
  {
    id: '10',
    name: 'Festival Fiasco Portapotty',
    location: { latitude: 51.4500, longitude: -0.1500 },
    address: 'Summer Sounds Festival, South Park',
    createdBy: 'user_abc123',
    createdAt: '2023-07-15T18:00:00Z',
    averageRating: 1.0,
    features: {
      accessible: false, babyChanging: false, free: false, genderNeutral: true, hasSoap: false, hasToiletPaper: false,
    },
    photoUrls: [], // No photo, to test placeholder
    reviewCount: 15,
    countryCode: 'GB',
    countryFlag: '🇬🇧',
    legacyReview: 'A crime scene. You have been warned.',
  },
];
